name: faiss
dependencies:
  - python=3.8
  - pip
  - chardet
  - pandas=1.5.3
  - pytorch::faiss-gpu
  - pip:
    - python-terrier==0.9.0
    - "--upgrade=git+https://github.com/terrierteam/pyterrier_colbert.git"